### ISSUE TITLE
Artigo faltando

### ISSUE THREAD

**Issue by gustavopinto** [aserg-ufmg/CoreBR#1]
Oi pessoal, 

esse artigo que sou co-autor não consta na listagem: http://dblp.uni-trier.de/rec/bibtex/conf/fase/LiuPL15

Talvez pq a busca foi feita pelo nome do meu orientador, na época, e esse artigo ele não é um dos co-autores?

Abraços

**Comment by mtov** [comment]
Oi Gustavo,

O problema deve ter sido resolvido (acho que sua origem foram múltiplas páginas no DBLP, que você tinha ou tem).

Você confere agora os papers e scores da UFPA em SE e PL?

**Comment by gustavopinto** [comment]
Perfeito!
