### ISSUE TITLE
Me adicionando

### ISSUE THREAD

**Issue by mauricioaniche** [aserg-ufmg/CoreBR#2]
Oi pessoal,

Me adicionem ao sistema?

Maurício Finavaro Aniche
Antigo: IME/USP
Agora: Assistant Professor at Delft University of Technology

Meu PID: 61/9679 (é esse o número que precisam?)

**Comment by mtov** [comment]
Oi Aniche,

O que acontece é que só estamos adicionando "pesquisadores de deptos brasileiros", o que não é mais seu caso. (De toda forma, acho que seus papers estão sendo contados no IME, pois o Gerosa ainda está no IME; digo, no nosso sistema).

De todo modo, obrigado pelo interesse! Qualquer feedback é sempre bem vindo.

**Comment by mauricioaniche** [comment]
Entendi, @mtov ! Obrigado pela resposta!
