### ISSUE TITLE
Número de Docentes da UFAL

### ISSUE THREAD

**Issue by marciomribeiro** [aserg-ufmg/CoreBR#3]
O número de docentes da UFAL é 2, e não 1. Temos:

- Márcio Ribeiro
- Baldoino Fonseca

**Comment by mtov** [comment]
Não seria 3?

Marcio Ribeiro, 
Baldoino Fonseca
Evandro Costa

**Comment by marciomribeiro** [comment]
Isso! Havia esquecido do Evandro!

**Comment by mtov** [comment]
ok, fechando então.
