### ISSUE TITLE
Universidades do paper "Smells are sensitive to developers"

### ISSUE THREAD

**Issue by marciomribeiro** [aserg-ufmg/CoreBR#4]
O referido paper só está registrado como da PUC-Rio.

No entanto, possui autores da UFAL e da UFCG também.

**Comment by mtov** [comment]
olás, para facilitar, poderiam indicar a instituição de cada autor desse paper? (só autores docentes)

**Comment by marciomribeiro** [comment]
Alessandro Garcia	PUC-Rio, Brazil
Nuno Antunes	University of Coimbra, Portugal
Baldoino Fonseca	UFAL, Brazil
Evandro Costa	UFAL, Brazil

**Comment by mtov** [comment]
Pronto, resolvido, favor testar (a dúvida surgiu porque mencionou UFCG, ao abrir a issue).

**Comment by marciomribeiro** [comment]
UFCG foi o aluno de Doutorado (primeiro autor). Perdão pela confusão! :)
